### ISSUE TITLE
Executable file

### ISSUE THREAD

**Issue by OrckOrck** [SpectralPlatypus/QuidditchArchiveTool#1]
Hi.
I want to translate HP: Quidditch World Cup into my native language, and I saw your wonderful program that open "ccd" files. 
But in READMY says about **QWCArchiveTool.exe**, but I do not see _any executable file_.
Can you help me?

**Comment by SpectralPlatypus** [comment]
Hey, sorry for the really late reply here. This repo only contains the source files for the build. I will go ahead and upload a pre-built exe in the upcoming days and you can use that directly

**Comment by SpectralPlatypus** [comment]
Uploaded v1.0 release, closing issue
